# coding=utf-8
####################################################
# PDF export for channel lists
#
# Author: Tobias Grupe
####################################################

import datetime
import os
import subprocess
import sys
import tempfile

from fpdf import FPDF, XPos, YPos

# (background RGB, text RGB) per channel color name
_CELL_COLORS = {
    "black":      ((31,  31,  31),  (255, 255, 255)),
    "red":        ((204,  31,  31), (255, 255, 255)),
    "green":      ((31,  158,  31), (255, 255, 255)),
    "blue":       ((31,   69, 204), (255, 255, 255)),
    "light blue": ((71,  158, 235), (0,   0,   0)),
    "yellow":     ((242, 224,  31), (0,   0,   0)),
    "purple":     ((128,  31, 184), (255, 255, 255)),
    "white":      ((242, 242, 242), (0,   0,   0)),
    "grey":       ((128, 128, 128), (255, 255, 255)),
    "orange":     ((235, 133,  31), (0,   0,   0)),
}

_COL_W = (12, 65, 35)  # mm: Ch, Name, Color
_ROW_H = 6             # mm


def _header_row(pdf):
    pdf.set_fill_color(46, 46, 46)
    pdf.set_text_color(255, 255, 255)
    pdf.set_draw_color(179, 179, 179)
    pdf.set_font("Helvetica", style="B", size=9)
    pdf.cell(_COL_W[0], _ROW_H, "Ch",    border=1, align="C", fill=True)
    pdf.cell(_COL_W[1], _ROW_H, "Name",  border=1, align="C", fill=True)
    pdf.cell(_COL_W[2], _ROW_H, "Color", border=1, align="C", fill=True,
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)


def export_pdf(filepath, channel_data, console_type):
    """Generate a channel-list PDF.

    channel_data: list of dicts with keys:
        dliveChannel (int), name (str), color (str)
    """
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=False)
    pdf.set_margins(15, 15, 15)
    pdf.add_page()

    page_bottom = pdf.h - 15

    # Title
    pdf.set_font("Helvetica", style="B", size=14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, f"Channel List - {console_type}", align="C",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Date
    date_str = datetime.datetime.now().strftime("%Y-%m-%d  %H:%M")
    pdf.set_font("Helvetica", size=9)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 5, f"Generated: {date_str}",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    _header_row(pdf)

    pdf.set_font("Helvetica", size=8)
    for i, d in enumerate(channel_data):
        if pdf.get_y() + _ROW_H > page_bottom:
            pdf.add_page()
            _header_row(pdf)
            pdf.set_font("Helvetica", size=8)

        ch_num = str(d["dliveChannel"])
        name = str(d.get("name", ""))
        color_raw = str(d.get("color", "")).lower().strip()

        alt_bg = (242, 242, 242) if i % 2 == 0 else (255, 255, 255)
        pdf.set_draw_color(179, 179, 179)

        pdf.set_fill_color(*alt_bg)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(_COL_W[0], _ROW_H, ch_num, border=1, align="C", fill=True)
        pdf.cell(_COL_W[1], _ROW_H, name,   border=1, align="C", fill=True)

        if color_raw in _CELL_COLORS:
            cell_bg, cell_fg = _CELL_COLORS[color_raw]
            pdf.set_fill_color(*cell_bg)
            pdf.set_text_color(*cell_fg)
        else:
            pdf.set_fill_color(*alt_bg)
            pdf.set_text_color(0, 0, 0)

        pdf.cell(_COL_W[2], _ROW_H, color_raw or "-", border=1, align="C", fill=True,
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(5)
    pdf.set_font("Helvetica", size=8)
    pdf.set_text_color(128, 128, 128)
    pdf.cell(0, 5, "Generated by dlive-midi-tools", align="C")

    pdf.output(filepath)


def make_temp_path():
    fd, path = tempfile.mkstemp(suffix=".pdf", prefix="dmt-channel-list-")
    os.close(fd)
    return path


def open_file(filepath):
    """Open the file with the OS default application (PDF viewer / print dialog)."""
    if sys.platform == "darwin":
        subprocess.run(["open", filepath])
    elif sys.platform == "win32":
        os.startfile(filepath)
    else:
        subprocess.run(["xdg-open", filepath])
