# coding=utf-8
####################################################
# PDF export for channel lists
#
# Author: Tobias Grupe
####################################################

import datetime
import os
import subprocess
import sys
import tempfile

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer

# (background color, text color) per channel color name
_CELL_COLORS = {
    "black":      (colors.Color(0.12, 0.12, 0.12), colors.white),
    "red":        (colors.Color(0.80, 0.12, 0.12), colors.white),
    "green":      (colors.Color(0.12, 0.62, 0.12), colors.white),
    "blue":       (colors.Color(0.12, 0.27, 0.80), colors.white),
    "light blue": (colors.Color(0.28, 0.62, 0.92), colors.black),
    "yellow":     (colors.Color(0.95, 0.88, 0.12), colors.black),
    "purple":     (colors.Color(0.50, 0.12, 0.72), colors.white),
    "white":      (colors.Color(0.95, 0.95, 0.95), colors.black),
    "grey":       (colors.Color(0.50, 0.50, 0.50), colors.white),
    "orange":     (colors.Color(0.92, 0.52, 0.12), colors.black),
}


def export_pdf(filepath, channel_data, console_type):
    """Generate a channel-list PDF.

    channel_data: list of dicts with keys:
        dliveChannel (int), name (str), color (str)
    """
    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        leftMargin=1.5 * cm, rightMargin=1.5 * cm,
        topMargin=1.5 * cm, bottomMargin=1.5 * cm,
    )
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph(f"Channel List — {console_type}", styles["Title"]))
    date_str = datetime.datetime.now().strftime("%Y-%m-%d  %H:%M")
    elements.append(Paragraph(f"Generated: {date_str}", styles["Normal"]))
    elements.append(Spacer(1, 0.4 * cm))

    rows = [["Ch", "Name", "Color"]]
    for d in channel_data:
        color_raw = str(d.get("color", "")).lower().strip()
        rows.append([str(d["dliveChannel"]), str(d.get("name", "")), color_raw if color_raw else "—"])

    table = Table(rows, colWidths=[1.2 * cm, 6.5 * cm, 3.5 * cm], repeatRows=1)

    style_cmds = [
        ("BACKGROUND",    (0, 0), (-1, 0),  colors.Color(0.18, 0.18, 0.18)),
        ("TEXTCOLOR",     (0, 0), (-1, 0),  colors.white),
        ("FONTNAME",      (0, 0), (-1, 0),  "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0),  9),
        ("FONTSIZE",      (0, 1), (-1, -1), 8),
        ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("GRID",          (0, 0), (-1, -1), 0.4, colors.Color(0.70, 0.70, 0.70)),
        ("LEFTPADDING",   (0, 0), (-1, -1), 4),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 4),
        ("TOPPADDING",    (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]

    # Alternating row background for Ch and Name columns
    for i in range(1, len(rows)):
        bg = colors.Color(0.95, 0.95, 0.95) if i % 2 == 0 else colors.white
        style_cmds.append(("BACKGROUND", (0, i), (1, i), bg))

    # Per-channel color cell
    for i, d in enumerate(channel_data, start=1):
        color_raw = str(d.get("color", "")).lower().strip()
        if color_raw in _CELL_COLORS:
            cell_bg, cell_fg = _CELL_COLORS[color_raw]
            style_cmds.append(("BACKGROUND", (2, i), (2, i), cell_bg))
            style_cmds.append(("TEXTCOLOR",  (2, i), (2, i), cell_fg))

    table.setStyle(TableStyle(style_cmds))
    elements.append(table)
    elements.append(Spacer(1, 0.5 * cm))
    elements.append(Paragraph("Generated by dlive-midi-tools", styles["Normal"]))

    doc.build(elements)


def make_temp_path():
    fd, path = tempfile.mkstemp(suffix=".pdf", prefix="dmt-channel-list-")
    os.close(fd)
    return path


def open_file(filepath):
    """Open the file with the OS default application (PDF viewer / print dialog)."""
    if sys.platform == "darwin":
        subprocess.run(["open", filepath])
    elif sys.platform == "win32":
        os.startfile(filepath)
    else:
        subprocess.run(["xdg-open", filepath])
